cmls/urls.py
from django.contrib import admin
from django.urls import include , path
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = "Cimas MedLabs laboratory System"
admin.site.index_title = 'Cimas MedLabs Laboratory Site Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    # path('visitor/',include('visitor.urls', namespace="visitor")),
    path('users/', include('django.contrib.auth.urls')),
    path('patient/',include('patient.urls', namespace="patient")),
    path('pathologist/',include('Lab_Pathologist.urls', namespace="pathologist")),
    path('doctor/',include('doctor.urls', namespace="doctor")),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.urls import path
from .views import (
                    doctor_dashboard, 
                    patients_home,
                    specimen_home,
                    dsamples_home,
                    specimen_details,
                    report_home,
                    report_details,
                    )


app_name = 'doctor'

urlpatterns = [
    path('doctor_dashboard/', doctor_dashboard, name='doctor_dashboard'),
    path('<int:id>/patients_home/', patients_home, name='patients_home'),
    path('<int:id>/specimen_home/', specimen_home, name='specimen_home'),
    path('specimen_home/<int:id>/specimen_details/', specimen_details, name='specimen_details'),
    path('<int:id>/samples_home/', dsamples_home, name='dsamples_home'),
    path('<int:id>/report_home/', report_home, name='report_home'),
    path('report_home/<int:id>/report_details/', report_details, name='report_details'),
]
 

patient/urls.py
from django.urls import path
from .views import (
                    patient_dashboard, 
                    add_specimen,
                    edit_specimen,
                    delete_specimen,
                    specimen_home,
                    send_specimen,
                    doctor_home,
                    doctors_details,
                    report_home,
                    report_details,
                    )


app_name = 'patient'

urlpatterns = [
    path('patient_dashboard/', patient_dashboard, name='patient_dashboard'),
    path('<int:id>/view_specimen/', specimen_home, name='specimen_home'),
    path('<int:id>/view_specimen/add_specimen/', add_specimen, name='add_specimen'),
    path('view_specimen/<int:id>/edit_specimen/', edit_specimen, name='edit_specimen'),
    path('view_specimen/<int:id>/delete_specimen/', delete_specimen, name='delete_specimen'),
    path('view_specimen/<int:id>/send_specimen/', send_specimen, name='send_specimen'),
    path('<int:id>/doctors_home/', doctor_home, name='doctor_home'),
    path('doctors_home/<int:id>/doctor_details/', doctors_details, name='doctors_details'),
    path('<int:id>/report_home/', report_home, name='report_home'),
    path('report_home/<int:id>/report_details/', report_details, name='report_details'),

]
 

doctor/models.py
from django.db import models
from django.utils import timezone
from users.models import User
from patient.models import Specimen


from datetime import datetime

dt = datetime.now()
milliseconds = int(round(dt.timestamp() *1000))
# print(milliseconds)

# Create your models here.
class Doctor(models.Model):
    user          = models.ForeignKey(User, default=1, on_delete = models.CASCADE)
    doctor_name   = models.CharField(max_length=200, blank=False)
    password      = models.CharField(max_length=200, blank=False)
    email         = models.CharField(max_length=200, blank=False)
    qualification = models.CharField(max_length=200, blank=False)
    age           = models.CharField(max_length=200, blank=False)
    gender        = models.CharField(max_length=200, null=False, blank=False)
    updated       = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp     = models.DateTimeField(auto_now=False, auto_now_add=True)


    def __str__(self):
        return self.doctor_name

    class Meta:
        ordering = ["-timestamp", "-updated"]


class SpecimenData(models.Model):
    patient       = models.ForeignKey(User, default=1, on_delete = models.CASCADE, related_name='patients')
    doctor        = models.ForeignKey(User, default=1, on_delete = models.CASCADE, related_name='doctors')
    specimen      = models.ForeignKey(Specimen, on_delete = models.CASCADE)
    reff          = models.CharField(max_length=200, blank=False, default = milliseconds)
    status        = models.CharField(max_length=200, blank=False, default="pending")
    pathologist   = models.CharField(max_length=200, blank=False, default = "no")
    temperature   = models.CharField(max_length=200, blank=True, null=True)
    weight        = models.CharField(max_length=200, blank=True, null=True)
    daysent       = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated       = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp     = models.DateTimeField(auto_now=False, auto_now_add=True)


    # def __str__(self):
    #     return self.reff

    class Meta:
        ordering = ["-timestamp", "-updated"]

patient/models.py
from django.db import models

from django.db import models
from users.models import User

# Create your models here.
class Specimen(models.Model):
    user          = models.ForeignKey(User, default=1, on_delete = models.CASCADE)
    patient_name  = models.CharField(max_length=200, blank=False)
    email         = models.CharField(max_length=200, blank=False)
    # specimen_name = models.CharField(max_length=200, blank=False)
    # hemoglobin    = models.CharField(max_length=200, blank=False)
    # RBC           = models.CharField(max_length=200, null=False, blank=False)
    gender        = models.CharField(max_length=200, blank=False)
    age           = models.CharField(max_length=200, blank=False)
    status        = models.CharField(max_length=200, blank=False, default="available")
    updated       = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp     = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.patient_name

    class Meta:
        ordering = ["-timestamp", "-updated"]

doctor/forms.py
from django import forms
from django.utils.translation import gettext as _
from .models import SpecimenData

class SpecimenDataForm(forms.ModelForm):

    class Meta:
        model = SpecimenData
        fields = ["temperature", "weight"]

patient/forms.py
from django import forms
from django.utils.translation import gettext as _
from .models import (
    Specimen,
)
from doctor.models import SpecimenData

class SpecimenForm(forms.ModelForm):

    class Meta:
        model = Specimen
        exclude = ('user', 'status',)
        fields = '__all__'


class SpecimenDataForm(forms.ModelForm):

    class Meta:
        model   = SpecimenData
        # exclude = ('patient',)
        fields  = '__all__'

doctor/views.py
from django.shortcuts import render, get_object_or_404, redirect
from users.models import User
from django.contrib.auth.decorators import login_required
from .models import SpecimenData
from Lab_Pathologist.models import GeneratedReport

from .forms import SpecimenDataForm

from django.contrib import messages
from django.template.loader import render_to_string

from django.db.models import Q

# Create your views here. 
@login_required
def doctor_dashboard(request):
    username = request.user.username
    id       = request.user.id
    doctor = User.objects.filter(id=id, is_doctor = True)
    print(doctor)

    context = {
        'doctor': doctor, 
        'username':username,
    }
    return render(request,'doctor/view.html', context)


@login_required
def patients_home(request,id):
    doctor      = get_object_or_404(User, pk=id)
    patients    = User.objects.filter(is_patient=True)
    username    = request.user.username

    context     = {
        "doctor"     : doctor,
        "patients"   : patients,
        "username"   : username,
    }
    return render(request,'patients/view.html', context)


@login_required
def specimen_home(request, id):
    specimendata    = SpecimenData.objects.filter(doctor=request.user)
    username        = request.user.username
    doctor          = get_object_or_404(User, pk=id)
    # print(specimendata)
    context     = {
        "specimendata"  : specimendata,
        "username"      : username,
        "doctor"        : doctor,
    }
    return render(request,'patients/specimen.html', context)


@login_required
def specimen_details(request, id):
    specimendata    = get_object_or_404(SpecimenData, pk=id)
    username        = request.user.username
    doctor          = specimendata.doctor
    print(specimendata)
    form            = SpecimenDataForm(request.POST or None, request.FILES or None, instance=specimendata)
    if form.is_valid():
        specimen = form.save(commit=False)
        specimen.pathologist = 'yes'
        specimen.save()
        messages.success(request, "Specimen has been successfully sent to the Pathologist !!!")
        return redirect('doctor:specimen_home', doctor.id)
    context     = {
        "specimendata"  : specimendata,
        "username"      : username,
        "doctor"        : doctor,
        "form"          : form,
    }
    return render(request,'patients/specimen_details.html', context)


@login_required
def dsamples_home(request, id):
    username        = request.user.username
    doctor          = get_object_or_404(User, pk=id)

    context     = {
        "username"      : username,
        "doctor"        : doctor,
    }
    return render(request,'doctor/dsamples.html', context)


@login_required
def report_home(request, id):
    specimendata    = SpecimenData.objects.filter(doctor=request.user)
    specimendata    = specimendata[0]
    print(specimendata)
    reportdata      = GeneratedReport.objects.filter(specimendata=specimendata)
    username        = request.user.username
    doctor          = get_object_or_404(User, pk=id)
    print(reportdata)
    context     = {
        "reportdata"    : reportdata,
        "username"      : username,
        "doctor"        : doctor,
    }
    return render(request,'dreport/view.html', context)


@login_required
def report_details(request, id):
    reportdata      = get_object_or_404(GeneratedReport, pk=id)
    username        = request.user.username
    doctor          = request.user
    print(reportdata)

    context     = {
        "reportdata"    : reportdata,
        "username"      : username,
        "doctor"        : doctor,
    }
    return render(request,'dreport/dreport_details.html', context)

patient/views.py
from django.shortcuts import render, get_object_or_404, redirect
from users.models import User
from .models import Specimen
from .forms import SpecimenForm, SpecimenDataForm
from django.contrib.auth.decorators import login_required
from doctor.models import SpecimenData, Doctor
from Lab_Pathologist.models import GeneratedReport

from datetime import datetime

from django.contrib import messages
from django.template.loader import render_to_string

from django.db.models import Q

# Create your views here. 
@login_required
def patient_dashboard(request):
    username = request.user.username
    id       = request.user.id
    patient  = User.objects.filter(id=id, is_patient = True)
    print(patient)

    context = {
        'patient': patient, 
        'username':username,
    }
    return render(request,'patient/view.html', context)


@login_required
def specimen_home(request,id):
    specimen   = Specimen.objects.filter(user=id)
    # specimen   = Specimen.objects.all() 
    patient    = get_object_or_404(User, pk=id)
    username   = request.user.username

    context     = {
        "specimen"  : specimen,
        "patient"   : patient,
        "username"  : username,
    }
    return render(request, 'patient/specimen.html', context)

@login_required
def add_specimen(request, id):
    form     = SpecimenForm(request.POST or None, request.FILES or None)
    username = request.user.username
    patient  = get_object_or_404(User, pk=id)

    if form.is_valid():
        specimen = form.save(commit=False)
        specimen.user = request.user
        specimen.save()
        messages.success(request, specimen.specimen_name + " has been successfully added !!!")
        return redirect('patient:specimen_home', patient.id)
    context = {
        'username': username,
        "form": form,
        'patient': patient,
        'header': 'Add a New Specimen',
        'save': 'Save',
        'title': 'Add Specimen',
    }
    return render(request, 'patient/add_specimen.html', context)


@login_required
def edit_specimen(request, id, template_name='patient/add_specimen.html'):
    specimen = get_object_or_404(Specimen, pk=id)
    patient  = specimen.user
    username = request.user.username

    form = SpecimenForm(request.POST or None, instance=specimen)
    if form.is_valid():
        update_specimen = form.save(commit=False)
        update_specimen.save()
        print(update_specimen)
        messages.success(request, update_specimen.specimen_name + " has been successfully Updated !!!")
        return redirect('patient:specimen_home', patient.id)

    context = { 'form':form, 
                'username':username,
                'patient':patient,
                'header': 'Update Specimen',
                'save': 'Update',
                'title': 'Edit Specimen',
            }
    return render(request, template_name, context)


@login_required
def delete_specimen(request, id):
    specimen = get_object_or_404(Specimen, pk=id)
    print(specimen)
    patient  = specimen.user
    username = request.user.username

    specimen.delete()
    messages.info(request, specimen.specimen_name + "Specimen has been successfully deleted !!!")
    return redirect('patient:specimen_home', patient.id)

@login_required
def send_specimen(request, id):
    # dt = datetime.now()
    # milliseconds = int(round(dt.timestamp() *1000))
    # print(milliseconds)
    form     = SpecimenDataForm(request.POST or None, request.FILES or None)
    username = request.user.username
    specimen = get_object_or_404(Specimen, pk=id)
    patient  = specimen.user
    doctor   = User.objects.filter(is_doctor = True)
    print(doctor[0].id)
    doctor   = doctor[0]

    # if form.is_valid():
    specimendata = form.save(commit=False)
    specimendata.patient  = patient
    specimendata.doctor   = doctor
    specimendata.specimen = specimen
    specimendata.save()
    specimen.status = 'sent'
    specimen.save()
    messages.success(request,"Specimen has been successfully sent to the Doctor !!!")
    return redirect('patient:specimen_home', patient.id)

@login_required
def doctor_home(request,id):
    patient    = get_object_or_404(User, pk=id)
    doctors    = Doctor.objects.all()
    username   = request.user.username

    context     = {
        "patient"    : patient,
        "doctors"    : doctors,
        "username"   : username,
    }
    return render(request,'padoctors/view.html', context)


@login_required
def doctors_details(request, id):
    docdata     = get_object_or_404(Doctor, pk=id)
    username    = request.user.username
    patient     = request.user
    print(patient)

    context     = {
        "patient"      : patient,
        "docdata"      : docdata,
        "username"     : username,
    }
    return render(request,'padoctors/doctor_details.html', context)

@login_required
def report_home(request, id):
    specimendata    = SpecimenData.objects.filter(patient=request.user)
    specimendata    = specimendata[0]
    print(specimendata)
    reportdata      = GeneratedReport.objects.filter(specimendata=specimendata)
    username        = request.user.username
    patient         = get_object_or_404(User, pk=id)
    print(reportdata)
    context     = {
        "reportdata"    : reportdata,
        "username"      : username,
        "patient"       : patient,
    }
    return render(request,'preport/view.html', context)


@login_required
def report_details(request, id):
    reportdata      = get_object_or_404(GeneratedReport, pk=id)
    username        = request.user.username
    patient         = request.user
    print(reportdata)

    context     = {
        "reportdata"    : reportdata,
        "username"      : username,
        "patient"       : patient,
    }
    return render(request,'preport/preport_details.html', context)

doctor/templates/patients/specimen.html
{% extends "dspecimen_base.html" %} {% block title %}Specimens Home{% endblock %} {% block specimen_active %}active{% endblock %} {% load staticfiles %} {% block body %}
<!--Start Contents-->
<div class="panel panel-default">
    <div class="panel-body">

        {% if messages %} {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button> {{ message }}
        </div>
        {% endfor %} {% endif %}

        <!-- <h3>All Products</h3> -->
        <p style="display:inline-block">
            <a type="submit" class="btn btn-lg btn-primary" href="{% url 'doctor:specimen_home' doctor.id %}">View All</a>
            <!-- <a type="submit" class="btn btn-lg btn-outline-primary" href="{% url 'doctor:specimen_home' doctor.id %}">View Under Tests</a>
            <a type="submit" class="btn btn-lg btn-outline-primary" href="{% url 'doctor:specimen_home' doctor.id %}">With Completed Tests</a> -->
        </p>

        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %}

        <table class="table">
            <thead>
                <tr>
                    <th>Reff No.</th>
                    <th>Patient No.</th>
                    <th>Gender</th>
                    <th>Date</th>
                    <th>Actions</th>

                </tr>
            </thead>
            <tbody>
                {% if specimendata %} {% for product in specimendata %}
                <tr>
                    <td>{{ product.reff }}</td>
                    <td>
                        P00{{ product.patient.id }}
                    </td>
                    <td>
                        {{ product.specimen.gender }}
                    </td>
                    <td>
                        {{ product.timestamp }}
                    </td>
                    <td>
                        {% if product %}
                        <a href="{% url 'doctor:specimen_details' product.id %}" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="product_id" value="{{ product.id }}" />
                                <button type="submit" class="btn btn-success btn-lg">
                                    <span class="glyphicon glyphicon-play"></span>&nbsp; View
                                </button>
                            </a> {% endif %} {% if product.pathologist == "yes" %}
                        <a href="#" style="display: inline;">
                                {% csrf_token %}
                                <button disabled="True" type="submit" class="btn btn-primary btn-lg">
                                    <span class="glyphicon glyphicon-edit"></span>&nbsp; Sent to Pathologist
                                </button>
                            </a> {% endif %}
                    </td>
                </tr>
                {% endfor %} {% else %}
                <h3>You don't have any Specimens at the moment</h3>
                {% endif %}
            </tbody>
        </table>

    </div>
</div>


<!--End Contents-->
{% endblock %}

doctor/templates/patients/specimen_details.html
{% extends "dspecimen_base.html" %} {% block title %}Specimen Details{% endblock %} {% block specimen_active %}active{% endblock %} {% load staticfiles %} {% block body %}
<!--Start Contents-->
<div class="panel panel-default">
    <div class="panel-body">

        {% if messages %} {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button> {{ message }}
        </div>
        {% endfor %} {% endif %} {% if specimendata.pathologist == "no" %} {% if form.errors %} {% for field in form %} {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %} {% endfor %} {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %} {% endif %} {% if messages %} {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button> {{ message }}
        </div>
        {% endfor %} {% endif %}

        <h1 style="text-align: center;color: #2196f3;width: 60%;">Enter Temperature and Weight</h1><br> {% if error_message %}
        <p><strong> error_message </strong></p>
        {% endif %}
        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data" style="width: 60%;">
            {% csrf_token %} {% for field in form %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <span class="text-danger small">{{ field.errors }}</span>
                </div>

                <label id="pname" class="control-label col-sm-4" for="product_name" style="font-size: larger;">{{ field.label_tag }}</label>
                <div class="col-sm-8" id="pinput">{{ field }}</div>
            </div>
            {% endfor %}
            <button id="savep" type="reset" class="btn btn-outline-danger btn-md">Cancel</button>
            <button id="savep" class="btn btn-outline-success btn-md">Send</button>
        </form>
        <div style="padding-top: 10%;"></div>
        {% endif %}



        <h1 style="text-align: center;color: #2196f3;">Specimen for Patient P00{{ specimendata.patient.id }}</h1>
        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %}

        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                {% if specimendata %}

                <tr>
                    <td>Reff No.</td>
                    <td>{{ specimendata.reff }}</td>
                </tr>

                <tr>
                    <td>Doctor</td>
                    <td>{{ specimendata.doctor }}</td>
                </tr>

                <tr>
                    <td>Patient Code</td>
                    <td>P00{{ specimendata.patient.id }}</td>
                </tr>

                <tr>
                    <td>Gender</td>
                    <td>{{ specimendata.specimen.gender }}</td>
                </tr>

                <tr>
                    <td>Age</td>
                    <td>{{ specimendata.specimen.age }}</td>
                </tr>

                {% if specimendata.temperature %}
                <tr>
                    <td>Temperature</td>
                    <td>{{ specimendata.temperature }} Degrees Celsius</td>
                </tr>
                {% endif %} {% if specimendata.weight %}
                <tr>
                    <td>Weight</td>
                    <td>{{ specimendata.weight }} Kgs</td>
                </tr>
                {% endif %}

                <tr>
                    <td>Sent to Pathologist</td>
                    <td>{{ specimendata.pathologist }}</td>
                </tr>

                <tr>
                    <td>Test Status</td>
                    <td>{{ specimendata.status }}</td>
                </tr>

                <tr>
                    <td>Date Time</td>
                    <td>{{ specimendata.timestamp }}</td>
                </tr>
                {% endif %}
            </tbody>
        </table>

    </div>
</div>


<!--End Contents-->
{% endblock %}

doctor/templates/patients/view.html
{% extends "patients_base.html" %} {% block title %}Patients Home{% endblock %} {% block product_active %}active{% endblock %} {% load staticfiles %} {% block body %}
<!--Start Contents-->
<div class="panel panel-default">
    <div class="panel-body">

        {% if messages %} {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button> {{ message }}
        </div>
        {% endfor %} {% endif %}

        <!-- <h3>All Products</h3> -->
        <p style="display:inline-block">
            <a type="submit" class="btn btn-lg btn-primary" href="{% url 'doctor:patients_home' doctor.id %}">View All</a>
            <!-- <a type="submit" class="btn btn-lg btn-outline-primary" href="{% url 'doctor:patients_home' doctor.id %}">View Under Tests</a>
            <a type="submit" class="btn btn-lg btn-outline-primary" href="{% url 'doctor:patients_home' doctor.id %}">With Completed Tests</a> -->
        </p>

        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %}

        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>ID</th>
                    <th>Gender</th>
                    <th>Email</th>
                    <th>Actions</th>

                </tr>
            </thead>
            <tbody>
                {% if patients %} {% for product in patients %}
                <tr>
                    <td>{{ product.username }}</td>
                    <td>
                        {{ product.id }}
                    </td>
                    <td>
                        {{ product.gender }}
                    </td>
                    <td>
                        {{ product.email }}
                    </td>
                    <td>
                        {% if product %}
                        <a href="{% url 'doctor:patients_home' product.id %}" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="product_id" value="{{ product.id }}" />
                                <button type="submit" class="btn btn-primary btn-lg">
                                    <span class="glyphicon glyphicon-play"></span>&nbsp; View Details
                                </button>
                            <!-- </a> {% endif %} {% if product %}
                        <a href="{% url 'doctor:patients_home' product.id %}" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="product_id" value="{{ product.id }}" />
                                <button type="submit" class="btn btn-primary btn-md">
                                    <span class="glyphicon glyphicon-edit"></span>&nbsp; Edit info
                                </button>
                            </a> {% endif %} -->
                    </td>
                </tr>
                {% endfor %} {% else %}
                <h3>You don't have any Patients at the moment</h3>
                {% endif %}
            </tbody>
        </table>

    </div>
</div>


<!--End Contents-->
{% endblock %}