cmls/urls.py
from django.contrib import admin
from django.urls import include , path
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = "Cimas MedLabs laboratory System"
admin.site.index_title = 'Cimas MedLabs Laboratory Site Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    # path('visitor/',include('visitor.urls', namespace="visitor")),
    path('users/', include('django.contrib.auth.urls')),
    path('patient/',include('patient.urls', namespace="patient")),
    path('pathologist/',include('Lab_Pathologist.urls', namespace="pathologist")),
    path('doctor/',include('doctor.urls', namespace="doctor")),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patient/urls.py
from django.urls import path
from .views import (
                    patient_dashboard, 
                    add_specimen,
                    edit_specimen,
                    delete_specimen,
                    specimen_home,
                    send_specimen,
                    doctor_home,
                    doctors_details,
                    report_home,
                    report_details,
                    )


app_name = 'patient'

urlpatterns = [
    path('patient_dashboard/', patient_dashboard, name='patient_dashboard'),
    path('<int:id>/view_specimen/', specimen_home, name='specimen_home'),
    path('<int:id>/view_specimen/add_specimen/', add_specimen, name='add_specimen'),
    path('view_specimen/<int:id>/edit_specimen/', edit_specimen, name='edit_specimen'),
    path('view_specimen/<int:id>/delete_specimen/', delete_specimen, name='delete_specimen'),
    path('view_specimen/<int:id>/send_specimen/', send_specimen, name='send_specimen'),
    path('<int:id>/doctors_home/', doctor_home, name='doctor_home'),
    path('doctors_home/<int:id>/doctor_details/', doctors_details, name='doctors_details'),
    path('<int:id>/report_home/', report_home, name='report_home'),
    path('report_home/<int:id>/report_details/', report_details, name='report_details'),

]
 

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (register_patient, home_page, registration_redirect, redirect_logged, dashboard, about, contact)

app_name = 'users'
urlpatterns = [
        path('login/', auth_views.LoginView.as_view(), name='login'),
        path('logout/', auth_views.LogoutView.as_view(), name='logout'),
        path('password-reset/',auth_views.PasswordResetView.as_view(template_name='reset/password_reset_form.html'),name='password_reset'),
        path('users/password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='reset/password_reset_done.html'),name='password_reset_done'),
        path('users/reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='reset/password_reset_confirm.html'),name='password_reset_confirm'),
        path('users/reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='reset/password_reset_complete.html'),name='password_reset_complete'),
        path('dash/',redirect_logged, name='dash'),
        path('admin/',  dashboard , name='dashboard'), 
        path('register/patient/', register_patient, name='register_patient'),
        path('register/', registration_redirect , name='registration_redirect'),
        path('aboutus/', about, name='about'),
        path('contact/', contact, name='contact'),
        path('', home_page, name='home_page'),
]

patient/models.py
from django.db import models

from django.db import models
from users.models import User

# Create your models here.
class Specimen(models.Model):
    user          = models.ForeignKey(User, default=1, on_delete = models.CASCADE)
    patient_name  = models.CharField(max_length=200, blank=False)
    email         = models.CharField(max_length=200, blank=False)
    # specimen_name = models.CharField(max_length=200, blank=False)
    # hemoglobin    = models.CharField(max_length=200, blank=False)
    # RBC           = models.CharField(max_length=200, null=False, blank=False)
    gender        = models.CharField(max_length=200, blank=False)
    age           = models.CharField(max_length=200, blank=False)
    status        = models.CharField(max_length=200, blank=False, default="available")
    updated       = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp     = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.patient_name

    class Meta:
        ordering = ["-timestamp", "-updated"]

patient/forms.py
from django import forms
from django.utils.translation import gettext as _
from .models import (
    Specimen,
)
from doctor.models import SpecimenData

class SpecimenForm(forms.ModelForm):

    class Meta:
        model = Specimen
        exclude = ('user', 'status',)
        fields = '__all__'


class SpecimenDataForm(forms.ModelForm):

    class Meta:
        model   = SpecimenData
        # exclude = ('patient',)
        fields  = '__all__'

patient/views.py
from django.shortcuts import render, get_object_or_404, redirect
from users.models import User
from .models import Specimen
from .forms import SpecimenForm, SpecimenDataForm
from django.contrib.auth.decorators import login_required
from doctor.models import SpecimenData, Doctor
from Lab_Pathologist.models import GeneratedReport

from datetime import datetime

from django.contrib import messages
from django.template.loader import render_to_string

from django.db.models import Q

# Create your views here. 
@login_required
def patient_dashboard(request):
    username = request.user.username
    id       = request.user.id
    patient  = User.objects.filter(id=id, is_patient = True)
    print(patient)

    context = {
        'patient': patient, 
        'username':username,
    }
    return render(request,'patient/view.html', context)


@login_required
def specimen_home(request,id):
    specimen   = Specimen.objects.filter(user=id)
    # specimen   = Specimen.objects.all() 
    patient    = get_object_or_404(User, pk=id)
    username   = request.user.username

    context     = {
        "specimen"  : specimen,
        "patient"   : patient,
        "username"  : username,
    }
    return render(request, 'patient/specimen.html', context)

@login_required
def add_specimen(request, id):
    form     = SpecimenForm(request.POST or None, request.FILES or None)
    username = request.user.username
    patient  = get_object_or_404(User, pk=id)

    if form.is_valid():
        specimen = form.save(commit=False)
        specimen.user = request.user
        specimen.save()
        messages.success(request, specimen.specimen_name + " has been successfully added !!!")
        return redirect('patient:specimen_home', patient.id)
    context = {
        'username': username,
        "form": form,
        'patient': patient,
        'header': 'Add a New Specimen',
        'save': 'Save',
        'title': 'Add Specimen',
    }
    return render(request, 'patient/add_specimen.html', context)


@login_required
def edit_specimen(request, id, template_name='patient/add_specimen.html'):
    specimen = get_object_or_404(Specimen, pk=id)
    patient  = specimen.user
    username = request.user.username

    form = SpecimenForm(request.POST or None, instance=specimen)
    if form.is_valid():
        update_specimen = form.save(commit=False)
        update_specimen.save()
        print(update_specimen)
        messages.success(request, update_specimen.specimen_name + " has been successfully Updated !!!")
        return redirect('patient:specimen_home', patient.id)

    context = { 'form':form, 
                'username':username,
                'patient':patient,
                'header': 'Update Specimen',
                'save': 'Update',
                'title': 'Edit Specimen',
            }
    return render(request, template_name, context)


@login_required
def delete_specimen(request, id):
    specimen = get_object_or_404(Specimen, pk=id)
    print(specimen)
    patient  = specimen.user
    username = request.user.username

    specimen.delete()
    messages.info(request, specimen.specimen_name + "Specimen has been successfully deleted !!!")
    return redirect('patient:specimen_home', patient.id)

@login_required
def send_specimen(request, id):
    # dt = datetime.now()
    # milliseconds = int(round(dt.timestamp() *1000))
    # print(milliseconds)
    form     = SpecimenDataForm(request.POST or None, request.FILES or None)
    username = request.user.username
    specimen = get_object_or_404(Specimen, pk=id)
    patient  = specimen.user
    doctor   = User.objects.filter(is_doctor = True)
    print(doctor[0].id)
    doctor   = doctor[0]

    # if form.is_valid():
    specimendata = form.save(commit=False)
    specimendata.patient  = patient
    specimendata.doctor   = doctor
    specimendata.specimen = specimen
    specimendata.save()
    specimen.status = 'sent'
    specimen.save()
    messages.success(request,"Specimen has been successfully sent to the Doctor !!!")
    return redirect('patient:specimen_home', patient.id)

@login_required
def doctor_home(request,id):
    patient    = get_object_or_404(User, pk=id)
    doctors    = Doctor.objects.all()
    username   = request.user.username

    context     = {
        "patient"    : patient,
        "doctors"    : doctors,
        "username"   : username,
    }
    return render(request,'padoctors/view.html', context)


@login_required
def doctors_details(request, id):
    docdata     = get_object_or_404(Doctor, pk=id)
    username    = request.user.username
    patient     = request.user
    print(patient)

    context     = {
        "patient"      : patient,
        "docdata"      : docdata,
        "username"     : username,
    }
    return render(request,'padoctors/doctor_details.html', context)

@login_required
def report_home(request, id):
    specimendata    = SpecimenData.objects.filter(patient=request.user)
    specimendata    = specimendata[0]
    print(specimendata)
    reportdata      = GeneratedReport.objects.filter(specimendata=specimendata)
    username        = request.user.username
    patient         = get_object_or_404(User, pk=id)
    print(reportdata)
    context     = {
        "reportdata"    : reportdata,
        "username"      : username,
        "patient"       : patient,
    }
    return render(request,'preport/view.html', context)


@login_required
def report_details(request, id):
    reportdata      = get_object_or_404(GeneratedReport, pk=id)
    username        = request.user.username
    patient         = request.user
    print(reportdata)

    context     = {
        "reportdata"    : reportdata,
        "username"      : username,
        "patient"       : patient,
    }
    return render(request,'preport/preport_details.html', context)

patient/templates/patient_base.html
<!DOCTYPE html>
<html>

<meta http-equiv="content-type" content="text/html;charset=UTF-8" />

<head>
    <title>{{ username }}|{% block title %} Patient|Dashboard {% endblock %}</title>


    {% load staticfiles %}

    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon" />

    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <!--external stylesheets-->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/pharmacy.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">

</head>

<body class="app">
    <link rel="stylesheet" href="{% static 'css/special.css' %}">
    <div id="loader">
        <div class="spinner"></div>
    </div>

    <script type="8a59f832a6944b345b3bc4ec-text/javascript">
        window.addEventListener('load', () => {
            const loader = document.getElementById('loader');
            setTimeout(() => {
                loader.classList.add('fadeOut');
            }, 300);
        });
    </script>

    <div id="container">
        <div class="sidebar">
            <div class="sidebar-inner">
                <div class="sidebar-logo">
                    <div class="peers ai-c fxw-nw">
                        <div class="peer peer-greed">
                            <a class="sidebar-link td-n" href="{% url 'patient:patient_dashboard' %}" class="td-n">
                                <div class="peers ai-c fxw-nw">
                                    <div class="peer">
                                        <div class="logo">
                                            <img src="{% static 'img/logo.png' %}" alt="logo">
                                        </div>
                                    </div>
                                    <div class="peer peer-greed">
                                        <h3 class="lh-1 mB-0 logo-text">Cimas MedLabs</h3>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="peer">
                            <div class="mobile-toggle sidebar-toggle">
                                <a href="#" class="td-n"><i class="ti-arrow-circle-left"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <ul class="sidebar-menu scrollable pos-r">
                    <li class="nav-item mT-30 {% block home_active %}{% endblock %}">
                        <a class="sidebar-link" href="{% url 'patient:patient_dashboard' %}" default>
                            <span class="icon-holder">
                                    <i class="c-blue-500 ti-home"></i> 
                                </span>
                            <span class="title">Dashboard</span>
                        </a>
                    </li>
                    {% for patient in patient %}
                    <li class="nav-item {% block doctor_active %}{% endblock %}">
                        <a class="sidebar-link" href="{% url 'patient:doctor_home' patient.id %}">
                            <span class="icon-holder">
                                    <i class="c-brown-500 ti-email"></i> 
                                </span>
                            <span class="title">View Doctor</span></a>
                    </li>
                    <li class="nav-item {% block report_active %}{% endblock %}">
                        <a class="sidebar-link" href="{% url 'patient:report_home' patient.id %}">
                            <span class="icon-holder">
                                        <i class="c-indigo-500 ti-share"></i> 
                                    </span>
                            <span class="title">View Reports</span>
                        </a>
                    </li>
                    {% endfor %}
                    <li class="nav-item {% block about_active %}{% endblock %}">
                        <a class="sidebar-link" href="{% url 'users:about' %}">
                            <span class="icon-holder">
                                        <i class="c-deep-purple-500 ti-comment-alt"></i> 
                                    </span>
                            <span class="title">About Us</span>
                        </a>
                    </li>
                    <li class="nav-item {% block contact_active %}{% endblock %}">
                        <a class="sidebar-link" href="{% url 'users:contact' %}">
                            <span class="icon-holder">
                                        <i class="c-indigo-500 ti-bar-chart"></i> 
                                    </span>
                            <span class="title">Contact Us</span>
                        </a>
                    </li>

                    <li class="nav-item {% block logout_active %}{% endblock %}">
                        <a class="sidebar-link" href="{% url 'users:logout' %}">
                            <span class="icon-holder">
                                            <i class="c-indigo-500 ti-bar-chart"></i> 
                                        </span>
                            <span class="title">Logout</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <!-- Page container -->
        <!-- Nav Bar -->

        <div class="page-container">
            <div class="header navbar">
                <div class="header-container">
                    <ul class="nav-left">
                        <li>
                            <a id="sidebar-toggle" class="sidebar-toggle" href="javascript:void(0);">
                                <i class="ti-menu" style="color: white;"></i>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="{% url 'patient:patient_dashboard' %}" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1">
                                <div class="peer">
                                    <i class="ti-briefcase pR-10" style="color: white;"></i>
                                    <span class="fsz-sm fw-600 white" style="color: white;">Dashboard</span>
                                </div>
                            </a>
                        </li>

                        {% for patient in patient %}
                        <li class="dropdown">
                            <a href="{% url 'patient:report_home' patient.id %}" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1">
                                <div class="peer">
                                    <i class="ti-briefcase pR-10" style="color: white;"></i>
                                    <span class="fsz-sm fw-600 white" style="color: white;">Test Report</span>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="{% url 'patient:doctor_home' patient.id %}" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1">
                                <div class="peer">
                                    <i class="ti-gift pR-10" style="color: white;"></i>
                                    <span class="fsz-sm fw-600 white" style="color: white;">Doctors</span>
                                </div>
                            </a>
                        </li>

                        <li class="dropdown">
                            <a href="{% url 'patient:specimen_home' patient.id %}" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1">
                                <div class="peer">
                                    <i class="ti-gift pR-10" style="color: white;"></i>
                                    <span class="fsz-sm fw-600 white" style="color: white;">View Specimen</span>
                                </div>
                            </a>
                        </li>

                        <li class="dropdown">
                            <a href="{% url 'patient:add_specimen' patient.id %}" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1">
                                <div class="peer">
                                    <i class="ti-gift pR-10" style="color: white;"></i>
                                    <span class="fsz-sm fw-600 white" style="color: white;">Add Specimen</span>
                                </div>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                    <li class="dropdown">

                        <ul class="nav-right">

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1" data-toggle="dropdown">
                                    <div class="peer">
                                        <i class="ti-user pR-10" style="color: white;"></i>
                                        <span class="fsz-sm fw-600 white" style="color: white;">{{ username }}</span>
                                    </div>
                                </a>
                                <ul class="dropdown-menu fsz-sm">
                                    <li>
                                        <a href="#" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                                            <i class="ti-settings mR-10"></i>
                                            <span>Setting</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                                            <i class="ti-user mR-10"></i>
                                            <span>Profile</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                                            <i class="ti-email mR-10"></i>
                                            <span>Messages</span>
                                        </a>
                                    </li>
                                    <li role="separator" class="divider"></li>
                                    <li>
                                        <a href="{% url 'users:logout' %}" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                                            <i class="ti-power-off mR-10"></i>
                                            <span class="fsz-sm fw-600 c-grey-900">Logout</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </div>
            </div>

            {% block body %} {% endblock %}

            <!-- <div style="padding: 20%;"></div> -->

            <div style="height: 500px;"></div>


            <footer class="footer bdT ta-c p-30 lh-0 fsz-sm c-grey-600">
                <span>Copyright © 2020 Designed by 
                <a href="#" target="_blank" title="Colorlib">Munyaradzi Dobbie</a>
                . All rights reserved.
            </span>
                <!-- Global site tag (gtag.js) - Google Analytics -->


                <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="8a59f832a6944b345b3bc4ec-text/javascript"></script>
                <script type="8a59f832a6944b345b3bc4ec-text/javascript">
                    window.dataLayer = window.dataLayer || [];

                    function gtag() {
                        dataLayer.push(arguments);
                    }
                    gtag('js', new Date());

                    gtag('config', 'UA-23581568-13');
                </script>

            </footer>
        </div>
    </div>

    <script type="8a59f832a6944b345b3bc4ec-text/javascript" src="{% static 'js/vendor.js' %}"></script>
    <script type="8a59f832a6944b345b3bc4ec-text/javascript" src="{% static 'js/bundle.js' %}"></script>
    <script src="{% static 'ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js' %}" data-cf-settings="8a59f832a6944b345b3bc4ec-|49" defer=""></script>

</body>

</html>