cmls/urls.py
from django.contrib import admin
from django.urls import include , path
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = "Cimas MedLabs laboratory System"
admin.site.index_title = 'Cimas MedLabs Laboratory Site Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    # path('visitor/',include('visitor.urls', namespace="visitor")),
    path('users/', include('django.contrib.auth.urls')),
    path('patient/',include('patient.urls', namespace="patient")),
    path('pathologist/',include('Lab_Pathologist.urls', namespace="pathologist")),
    path('doctor/',include('doctor.urls', namespace="doctor")),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (register_patient, home_page, registration_redirect, redirect_logged, dashboard, about, contact)

app_name = 'users'
urlpatterns = [
        path('login/', auth_views.LoginView.as_view(), name='login'),
        path('logout/', auth_views.LogoutView.as_view(), name='logout'),
        path('password-reset/',auth_views.PasswordResetView.as_view(template_name='reset/password_reset_form.html'),name='password_reset'),
        path('users/password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='reset/password_reset_done.html'),name='password_reset_done'),
        path('users/reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='reset/password_reset_confirm.html'),name='password_reset_confirm'),
        path('users/reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='reset/password_reset_complete.html'),name='password_reset_complete'),
        path('dash/',redirect_logged, name='dash'),
        path('admin/',  dashboard , name='dashboard'), 
        path('register/patient/', register_patient, name='register_patient'),
        path('register/', registration_redirect , name='registration_redirect'),
        path('aboutus/', about, name='about'),
        path('contact/', contact, name='contact'),
        path('', home_page, name='home_page'),
]

visitor/models.py
from django.db import models

# Create your models here.

visitor/views.py
from django.shortcuts import render

# Create your views here.

visitor/templates/base_visitor.html
<!DOCTYPE html>
<html>

<meta http-equiv="content-type" content="text/html;charset=UTF-8" />

<head>
    <title>{% block title %} Cimas MedLabs laboratory {% endblock %}</title>


    {% load staticfiles %}

    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/registration.css' %}">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">

</head>

<body class="app">
    <link rel="stylesheet" href="{% static 'css/special.css' %}">
    <div id="loader">
        <div class="spinner"></div>
    </div>

    <script type="8a59f832a6944b345b3bc4ec-text/javascript">
        window.addEventListener('load', () => {
            const loader = document.getElementById('loader');
            setTimeout(() => {
                loader.classList.add('fadeOut');
            }, 300);
        });
    </script>




    <div id="container">
        <div class="sidebar">
            <div class="sidebar-inner">
                <div class="sidebar-logo">
                    <div class="peers ai-c fxw-nw">
                        <div class="peer peer-greed">
                            <a class="sidebar-link td-n" href="{% url 'users:home_page' %}" class="td-n">
                                <div class="peers ai-c fxw-nw">
                                    <div class="peer">
                                        <div class="logo">
                                            <img src="{% static 'img/logo.png' %}" alt="logo">
                                        </div>
                                    </div>
                                    <div class="peer peer-greed">
                                        <h3 class="lh-1 mB-0 logo-text">Cimas MedLabs</h3>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="peer">
                            <div class="mobile-toggle sidebar-toggle">
                                <a href="#" class="td-n"><i class="ti-arrow-circle-left"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <ul class="sidebar-menu scrollable pos-r">
                    <li class="nav-item mT-30 active">
                        <a class="sidebar-link" href="{% url 'users:home_page' %}" default>
                            <span class="icon-holder">
                                    <i class="c-blue-500 ti-home"></i> 
                                </span>
                            <span class="title">Login</span>
                        </a>
                    </li>
                    <!-- <li class="nav-item {% block calender_active %}{% endblock %}">
                        <a class="sidebar-link" href="#">
                            <span class="icon-holder">
                                        <i class="c-deep-orange-500 ti-calendar"></i> 
                                    </span>
                            <span class="title">Help</span>
                        </a>
                    </li> -->
                    <li class="nav-item {% block about_active %}{% endblock %}">
                        <a class="sidebar-link" href="{% url 'users:about' %}">
                            <span class="icon-holder">
                                        <i class="c-deep-purple-500 ti-comment-alt"></i> 
                                    </span>
                            <span class="title">About Us</span>
                        </a>
                    </li>
                    <li class="nav-item {% block contact_active %}{% endblock %}">
                        <a class="sidebar-link" href="{% url 'users:contact' %}">
                            <span class="icon-holder">
                                        <i class="c-indigo-500 ti-bar-chart"></i> 
                                    </span>
                            <span class="title">Contact Us</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <!-- Page container -->
        <!-- Nav Bar -->

        <div class="page-container">
            <div class="header navbar">
                <div class="header-container">
                    <ul class="nav-left">
                        <li>
                            <a id="sidebar-toggle" class="sidebar-toggle" href="javascript:void(0);">
                                <i class="ti-menu" style="color: white;"></i>
                            </a>
                        </li>

                        <li class="dropdown active">
                            <a href="{% url 'users:about' %}" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1">
                                <div class="peer">
                                    <i class="ti-world pR-10" style="color: white;"></i>
                                    <span class="fsz-sm fw-600 white" style="color: white;">About Us</span>
                                </div>
                            </a>
                        </li>

                        <li class="dropdown">
                            <a href="{% url 'users:contact' %}" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1">
                                <div class="peer">
                                    <i class="ti-world pR-10" style="color: white;"></i>
                                    <span class="fsz-sm fw-600 white" style="color: white;">Contact Us</span>
                                </div>
                            </a>
                        </li>

                        <li class="search-box">
                            <a class="search-toggle no-pdd-right" href="javascript:void(0);">
                                <i class="search-icon ti-search pdd-right-10" style="color: white;"></i>
                                <i class="search-icon-close ti-close pdd-right-10" style="color: white;"></i>
                            </a>
                        </li>

                    </ul>

                    <ul class="nav-right">
                        <li class="dropdown  {% block login_active %}{% endblock %}">
                            <a href="{% url 'users:login' %}" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1">
                                <div class="peer">
                                    <i class="ti-help pR-10" style="color: white;"></i>
                                    <span class="fsz-sm fw-600 white" style="color: white;">Login</span>
                                </div>
                            </a>
                        </li>

                        <li class="dropdown">
                            <a href="{% url 'users:registration_redirect' %}" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1">
                                <div class="peer">
                                    <i class="ti-user pR-10" style="color: white;"></i>
                                    <span class="fsz-sm fw-600 white" style="color: white;">Join Us</span>
                                </div>
                            </a>
                        </li>

                    </ul>
                </div>
            </div>

            {% block body %} {% endblock %}

            <div style="padding: 20%;"></div>


            <footer class="footer bdT ta-c p-30 lh-0 fsz-sm c-grey-600">
                <span>Copyright © 2020 Designed by 
                    <a href="#" target="_blank" title="Colorlib">Munyaradzi Dobbie</a>
                    . All rights reserved.
                </span>
                <!-- Global site tag (gtag.js) - Google Analytics -->


                <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="8a59f832a6944b345b3bc4ec-text/javascript"></script>
                <script type="8a59f832a6944b345b3bc4ec-text/javascript">
                    window.dataLayer = window.dataLayer || [];

                    function gtag() {
                        dataLayer.push(arguments);
                    }
                    gtag('js', new Date());

                    gtag('config', 'UA-23581568-13');
                </script>

            </footer>
        </div>
    </div>

    <script type="8a59f832a6944b345b3bc4ec-text/javascript" src="{% static 'js/vendor.js' %}"></script>
    <script type="8a59f832a6944b345b3bc4ec-text/javascript" src="{% static 'js/bundle.js' %}"></script>
    <script src="{% static 'ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js' %}" data-cf-settings="8a59f832a6944b345b3bc4ec-|49" defer=""></script>

</body>

</html>

visitor/templates/visitor_about.html
{% extends 'base_visitor.html' %}
{% block title %}About Us{% endblock %}
{% block about_active %}active{% endblock %}

{% block body %}

<main class="main-content bgc-grey-100">
    <div id="mainContent">
        <div class="full-container">
            <div class="email-app">

				{% include 'about_template.html' %} 


         	</div>
        </div>
    </div>
</main>		

{% endblock %}

visitor/templates/visitor_contact.html
{% extends 'base_visitor.html' %}
{% block title %}Contact Us{% endblock %}
{% block contact_active %}active{% endblock %}

{% block body %}

<main class="main-content bgc-grey-100">
    <div id="mainContent">
        <div class="full-container">
            <div class="email-app">

				{% include 'contact_template.html' %}


         	</div>
        </div>
    </div>
</main>		

{% endblock %}